In [32]:
import pandas as pd
import numpy as np
import glob

In [33]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [34]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

In [35]:
df = pd.read_csv('combined_csv.csv')

In [36]:
len(df[df['County'] == 'Hamilton'])

210

In [37]:
len(df)

40551

In [39]:
df_hamilton = df[df['County'] == 'Hamilton']

In [40]:
df_hamilton

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
150,Indiana,Hamilton,1985,123,60,46,13,4,0,0,190,112,51,0,0,123,0,0,0
425,Ohio,Hamilton,1985,365,30,125,192,17,1,0,210,139,105,2,34,36,293,0,0
521,Tennessee,Hamilton,1985,365,260,78,22,5,0,0,177,93,40,0,0,365,0,0,0
895,Indiana,Hamilton,1991,179,109,49,18,3,0,0,166,105,46,0,0,179,0,0,0
1192,New York,Hamilton,1991,146,134,8,4,0,0,0,147,48,31,0,0,141,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39536,Ohio,Hamilton,1989,365,92,161,89,22,1,0,205,137,75,6,70,72,192,0,25
39644,Tennessee,Hamilton,1989,308,219,63,22,4,0,0,182,93,42,0,0,289,0,0,19
39997,Indiana,Hamilton,1988,207,105,50,25,25,2,0,203,159,50,0,0,207,0,0,0
40301,Ohio,Hamilton,1988,366,97,148,80,32,9,0,222,161,79,1,86,86,192,0,1
40403,Tennessee,Hamilton,1988,366,232,66,44,21,3,0,210,133,43,0,0,350,0,0,16

In [41]:
df_hamilton.to_csv('hamilton.csv')